### ISSUE TITLE
Error when Entering

### ISSUE THREAD

**Issue by GuilhermeVasconcelos1** [SubmergedAmongUs/Submerged#127]
Error when entering
Hello, I want to report a "bug" that started happening to me with the Submerged mod. When doing the tutorial and entering Among Us, a "CMD" Command Prompt and some red texts appear and the game closes. If you can help me fix this "bug" I will be very happy. I'm an Among us player at Epic Games. Thank you and have a good day.

1. Go to 'Epic Games/AmongUs'
2. Click on 'Among Us'
3. Enter Among Us

I expected it to open Among Us because on your Submerged github it says that it has been tested and that it works on Epic Games' Among Us

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.7.12e]
 - Submerged: [e.g. 2023.8.2e]
 
Log

[Message: Preloader] BepInEx 6.0.0-be.671 - Among Us
[Message: Preloader] Built from commit 9caf61dca07043beae57b0771f6a5283aa02436b
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 32-bit (x86)
[Info   :   BepInEx] Running under Unity 2020.3.45f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): A mensagem recebida é inesperada ou tem a formatação incorreta.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

Screenshot
![SubmergedError](https://github.com/SubmergedAmongUs/Submerged/assets/147332723/6c528edf-6480-4af6-96e8-a067d4fef9d7)

**Comment by GuilhermeVasconcelos1** [comment]
What do you mean by problems with the internet and file permissions?

**Comment by GuilhermeVasconcelos1** [comment]
I think MY question was quite direct to the point that I had to repeat it, I went to check if it had to do with the internet and Antivirus, now the question is what the heck YOU mean by File permissions.

**Comment by GuilhermeVasconcelos1** [comment]
Very ignorant.
