### ISSUE TITLE
Keep Getting stuck in the choosing floor screen

### ISSUE THREAD

**Issue by DoudaKarma** [SubmergedAmongUs/Submerged#78]
**Describe the bug**
Game freeze when we have to choose where to spawn
**To Reproduce**
Just start a game with people and it get stuck 

**Expected behavior**
I expect to start the game

**Version 
 - Among Us: [e.g. 2023.6.20-beta.1]
 - Submerged: [e.g. 2023.6.13s]

**Additional context**
Was playing with my friends to try it but when we start and have to choose the floor it freezes abd it doesn't start it keep saying 5/5  (we were 5).

**Comment by Zeo666** [comment]
This error is spammed when the above happens

```
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.TypeInitializationException: The type initializer for 'Submerged.Utilities.Il2CppListEnumerable`1' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'method')
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
   at Submerged.Utilities.Il2CppListEnumerable`1..cctor() in C:\Repos\Submerged\Client\Submerged\Utilities\Il2CppListEnumerable.cs:line 36
   --- End of inner exception stack trace ---
   at Submerged.Systems.SpawnIn.SubmarineSpawnInSystem.Detoriorate(Single deltaTime) in C:\Repos\Submerged\Client\Submerged\Systems\SpawnIn\SubmarineSpawnInSystem.cs:line 34
   at Trampoline_VoidThisSingleSubmerged.Systems.SpawnIn.SubmarineSpawnInSystemDetoriorate(IntPtr , Single , Il2CppMethodInfo* )
```

**Comment by Alexejhero** [comment]
You are using an old version of the `BepInEx/core/Il2CppInterop.*.dll` files. Please use the ones from the Submerged release instead

**Comment by DoudaKarma** [comment]
That's what i have

**Comment by Alexejhero** [comment]
Could you please upload the log file so i can take a look at the error?

**Comment by DoudaKarma** [comment]
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11806330/LogOutput.log)

**Comment by Alexejhero** [comment]
The only error in the the log is coming from TheOtherRoles. TOR hasn't updated for the latest version yet so it will not work.

> [Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at InnerNet.InnerNetClient.SendOrDisconnect (Hazel.MessageWriter msg) [0x00000] in <00000000000000000000000000000000>:0 
  at InnerNet.InnerNetClient.FinishRpcImmediately (Hazel.MessageWriter msg) [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---
>
>   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at InnerNet.InnerNetClient.FinishRpcImmediately(MessageWriter msg)
   at TheOtherRoles.Helpers.shareGameVersion()
   at TheOtherRoles.Patches.GameStartManagerPatch.GameStartManagerUpdatePatch.Postfix(GameStartManager __instance)
   at DMD<GameStartManager::Update>(GameStartManager this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )

**Comment by DoudaKarma** [comment]
i didn't even download it maybe i need to redownload it then

**Comment by DoudaKarma** [comment]
OH WAIT FUCK i sended the wrong log i'm sorry i sended from another version of among us

**Comment by DoudaKarma** [comment]
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11806465/LogOutput.log)

**Comment by Alexejhero** [comment]
You are using an old version of the `BepInEx/core/Il2CppInterop.*.dll` files. Please use the ones from the Submerged.zip release download instead. 

Alternatively, here are just the interop files that you can replace in your among us folder:

[Il2CppInterop.zip](https://github.com/SubmergedAmongUs/Submerged/files/11806776/Il2CppInterop.zip)

**Comment by DoudaKarma** [comment]
ok i see well thank you for your help and thank you for you job on this update

**Comment by Alexejhero** [comment]
let me know if that solves your issue

**Comment by DoudaKarma** [comment]
okay i will

**Comment by DoudaKarma** [comment]
Ok it is now working thx

**Comment by Alexejhero** [comment]
Glad to hear

**Comment by tartsharpcobra** [comment]
niiice
